version: '3'
services:
  redis-cache:
    build: ./redis-cache
    image: rdangi81/redis-cache
    restart: always
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    restart: always
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    user: root
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - JVM_OPTS=-Xmx256m -Xms256m -XX:MaxPermSize=256m
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.1
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash

  registry-service:
    build: ./registry-service
    image: rdangi81/registry-service
    restart: always
    ports:
      - "8761:8761"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  config-server:
    build: ./config-server
    image: rdangi81/config-server
    restart: always
    ports:
      - "8888:8888"
    environment:
      - REDIS_HOST=redis-cache
      - REGISTRY_HOST=registry-service
      - ZIPKIN_HOST=zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - registry-service
      - zipkin

  gateway-service:
    build: ./gateway-service
    image: rdangi81/gateway-service
    ports:
      - "9500:9500"
    environment:
      - REGISTRY_HOST=registry-service
      - ZIPKIN_HOST=zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - registry-service
      - zipkin

  spring-boot-admin:
    build: ./spring-boot-admin
    image: rdangi81/spring-boot-admin
    ports:
      - "9000:9000"
    environment:
      - REGISTRY_HOST=registry-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - registry-service

  hello-service:
    build: ./hello-service
    image: rdangi81/hello-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis-cache
      - REGISTRY_HOST=registry-service
      - ZIPKIN_HOST=zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    restart: on-failure
