server:
  port: 9500

gateway:
  target:
    url:
      hello-service: lb://hello-service

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: hello-service
        uri: ${gateway.target.url.hello-service}
        predicates:
        - Path=/hello/**

eureka:
  client:
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
   
