server:
  port: 9500

gateway:
  target:
    url:
      hello-service: http://localhost:8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
      - id: hello-service
        uri: ${gateway.target.url.hello-service}
        predicates:
        - Path=/hello/**
