server:
  port: 8761

spring:
  application:
    name: registry-service
  zipkin:
    enabled: false

eureka:
  instance:
    hostname: ${spring.application.name:registry-service}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/
