server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amiyasahu/spring-cloud-config-server
          cloneOnStart: true
          searchPaths: '{application}'
  zipkin:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
