server:
  port: 9000

spring:
  application:
    name: spring-boot-admin

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
